INSERT INTO governorates (code, name_ar, name_en)
VALUES
('C', N'القاهرة', 'Cairo'),
('GZ', N'الجيزة', 'Giza'),
('ALX', N'الإسكندرية', 'Alexandria'),
('DK', N'الدقهلية', 'Dakahlia'),
('SHR', N'الشرقية', 'Sharqia'),
('MNF', N'المنوفية', 'Monufia'),
('BH', N'البحيرة', 'Beheira'),
('KFS', N'كفر الشيخ', 'Kafr El Sheikh'),
('GH', N'الغربية', 'Gharbia'),
('DM', N'دمياط', 'Damietta'),
('PS', N'بورسعيد', 'Port Said'),
('IS', N'الإسماعيلية', 'Ismailia'),
('SUZ', N'السويس', 'Suez'),
('SHN', N'شمال سيناء', 'North Sinai'),
('SHS', N'جنوب سيناء', 'South Sinai'),
('FYM', N'الفيوم', 'Faiyum'),
('BNI', N'بني سويف', 'Beni Suef'),
('MNY', N'المنيا', 'Minya'),
('AST', N'أسيوط', 'Assiut'),
('SOH', N'سوهاج', 'Sohag'),
('QNA', N'قنا', 'Qena'),
('LXR', N'الأقصر', 'Luxor'),
('ASN', N'أسوان', 'Aswan'),
('RDS', N'البحر الأحمر', 'Red Sea'),
('WJD', N'الوادي الجديد', 'New Valley'),
('MT', N'مطروح', 'Matrouh');
